# Site Configuration
# Edit this file to customize your documentation site

# Basic Info
title: My Documentation
description: Documentation for my project
logo: MyDocs

# Base path for GitHub Pages deployment (e.g., /repo-name)
# Leave empty for root domain deployment
# base: /my-repo

# Links (optional)
github: https://github.com

# SEO (optional)
# og_image: /og-image.png
# twitter_handle: "@handle"
